### PR TITLE
assembly-language: Add minor fixups

### PR DESCRIPTION
**Pull request by mariasfiraiala**
Change headings and fix some typos.

### CODE REVIEW

**Comment by mariasfiraiala** [comment]
@teodutu Before you jump on me, there are some linter issues. I've resolved a bunch of them, I just think the remaining ones are over the top (and I simply don't know how to replace `<br>` in order to still get a pretty newline).

**Comment by teodutu** [comment]
> @teodutu Before you jump on me

That's what she said.

> there are some linter issues. I've resolved a bunch of them, I just think the remaining ones are over the top (and I simply don't know how to replace `<br>` in order to still get a pretty newline).

Make a PR and add `br` to the `allowed_elements` array here [1]. After it's merged, `push -f` this PR to retrigger the action.

[1] https://github.com/security-summer-school/actions/blob/e1c1f66ef1eb8d21dcfd0bbd07fbf5370b67ceb1/super-linter/config/config.json#L7

**Comment by mariasfiraiala** [comment]
@teodutu Then, we shall wait for security-summer-school/actions#2 to get merged.

**Comment by teodutu** [comment]
> @teodutu Then, we shall wait for [security-summer-school/actions#2](https://github.com/security-summer-school/actions/pull/2) to get merged.

If only I had permission to merge it... @gabrielmocanu, go for it.

**Comment by teodutu** [comment]
@mariasfiraiala, https://github.com/security-summer-school/actions/pull/2 is merged. Try to rebase this PR now.

**Review by teodutu — APPROVED** [review]
:ok_hand:

**Pull request merged**
