### PR TITLE
application-lifetime: Fix some minor typos

### PR DESCRIPTION
**Pull request by mariasfiraiala**

### CODE REVIEW

**Review by cristian-vijelie — APPROVED** [review]
Good to go

**Review by teodutu — CHANGES_REQUESTED** [review]
Just remove the TOC altogether. IDK why we keep it.

**Comment by mariasfiraiala** [comment]
@teodutu Done with the TOC.

**Review by teodutu — CHANGES_REQUESTED** [review]
Add a commit description to pacify checkpatch. The superlinter error at line 219 is easy to fix (`;` counts as the end of a sentence). For the error about starting the document with a `#` heading (about which I told @cristian-vijelie again), just delete one `#` from each heading and they should be fine.

**Comment by teodutu** [comment]
FML I didn't know about this error [1] :))). Change of plans: change the headings back to what they were and just add the title "Application Lifetime" as a level 1 heading.

[1] https://github.com/security-summer-school/essentials/actions/runs/5608020484/jobs/10259859604?pr=40#step:3:654

**Comment by cristian-vijelie** [comment]
I did tell you about both errors :)

**Comment by mariasfiraiala** [comment]
Aight, done with that as well.

**Review by teodutu — APPROVED** [review]
:heart:

**Pull request merged**
